name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install
        run: npm install
      - name: Build
        run: npm run-script build
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.0
        with:
          build-directory: "build/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
